test mqtt command input

diff --git a/support/btle b/support/btle
--- a/support/btle
+++ b/support/btle
@@ -16,8 +16,8 @@
 # PROCESS BLUETOOTH PACKETS
 # ----------------------------------------------------------------------------------------
 
-btle_packet_processor () {
-	#POPULATE PACKET 
+btle_packet_processor() {
+	#POPULATE PACKET
 	local packet=$(echo "$1" | sed 's/> *//g')
 
 	#BEACON PACKET?
@@ -32,7 +32,7 @@ btle_packet_processor () {
 		local MINOR=$(echo $packet | sed 's/^.\{123\}\(.\{5\}\).*$/\1/')
 		local POWER=$(echo $packet | sed 's/^.\{129\}\(.\{2\}\).*$/\1/')
 		local UUID=$(echo $UUID | sed -e 's/\ //g' -e 's/^\(.\{8\}\)\(.\{4\}\)\(.\{4\}\)\(.\{4\}\)\(.\{12\}\)$/\1-\2-\3-\4-\5/')
-	
+
 		#MAJOR CALCULATION
 		MAJOR=$(echo $MAJOR | sed 's/\ //g')
 		MAJOR=$(echo "ibase=16; $MAJOR" | bc)
@@ -50,41 +50,40 @@ btle_packet_processor () {
 		RSSI=$(echo "ibase=16; $RSSI" | bc)
 		RSSI=$((RSSI - 256))
 
-        #CLEAR PACKET
-        packet=""
+		#CLEAR PACKET
+		packet=""
 
 		#SEND TO MAIN LOOP
-		[ ! -z "$UUID" ] && echo "BEAC$UUID|$MAJOR|$MINOR|$RSSI|$POWER|$received_mac_address" > main_pipe 
+		[ ! -z "$UUID" ] && echo "BEAC$UUID|$MAJOR|$MINOR|$RSSI|$POWER|$received_mac_address" | mqtt_pipe_send
 	fi
 }
-
 
 # ----------------------------------------------------------------------------------------
 # BLUETOOTH LE BACKGROUND SCANNING
 # ----------------------------------------------------------------------------------------
-btle_scanner () {
-	while true; do 
+btle_scanner() {
+	while true; do
 		#TIMEOUT THE HCITOOL SCAN TO RESHOW THE DUPLICATES WITHOUT SPAMMING THE MAIN LOOP BY USING THE --DUPLICATES TAG
 		local hcitool_raw=$(timeout --signal SIGINT 60 hcitool -i $PREF_HCI_DEVICE lescan 2>&1)
 
-		#FIND ERROR VALUES 
+		#FIND ERROR VALUES
 		local error=$(echo "$hcitool_raw" | grep -iE 'input/output error|invalid device|invalid|error|network')
 
 		#PUBLISH ERRORS BACK TO MAIN LOOP
-		if [ -n "$error" ]; then 
+		if [ -n "$error" ]; then
 
-			(>&2 echo "error! attempting to correct $PREF_HCI_DEVICE hardware fault.")
+			(echo >&2 "error! attempting to correct $PREF_HCI_DEVICE hardware fault.")
 
 			#POWER CYCLE
 			hciconfig $PREF_HCI_DEVICE down
-			sleep 5 
+			sleep 5
 			hciconfig $PREF_HCI_DEVICE up
 
 			continue
-		fi 
+		fi
 
-		#SEND SIGNAL THAT 
-		echo "BOFF" > main_pipe & 
+		#SEND SIGNAL THAT
+		echo "BOFF" | mqtt_pipe_send &
 		disown "$!"
 
 		#NEED DELAY TO BE SURE WE'RE NOT RESTARTING HARDWARE TOO QUICKLY
@@ -92,19 +91,18 @@ btle_scanner () {
 	done
 
 	#REPORT ERROR
-	(>&2 echo "error! irrecoverable btle_scanner error")
+	(echo >&2 "error! irrecoverable btle_scanner error")
 }
 
 #----------------------------------------------------------------------------------------
 # PROCESS BLUETOOTH PACKETS
 # ----------------------------------------------------------------------------------------
 
-trim_whitespace () {
+trim_whitespace() {
 	[[ "$1" =~ [^[:space:]](.*[^[:space:]])? ]] && printf "%s" "$BASH_REMATCH"
 }
 
-
-btle_text_processor () {
+btle_text_processor() {
 	local received_mac_address
 	local packet
 	local pdu_type
@@ -121,137 +119,136 @@ btle_text_processor () {
 	local uuid
 	local tx_power
 
-
- 	if [ -n "$1" ]; then 
- 		#DEFINE PACKET VARIABLE
- 		packet="$1"
+	if [ -n "$1" ]; then
+		#DEFINE PACKET VARIABLE
+		packet="$1"
 
 		#RETUREN FROM NAME REQUEST
-		if [[ $packet =~ Event:\ Remote ]]; then 
+		if [[ $packet =~ Event:\ Remote ]]; then
 			return 0
 		fi
-		
+
 		#------------ MAC ADDRESS
-		if [[ $packet =~ Address:\ ([^|\(]*)\  ]]; then 
+		if [[ $packet =~ Address:\ ([^|\(]*)\  ]]; then
 			received_mac_address=${BASH_REMATCH[1]}
 			received_mac_address=${received_mac_address^^}
-		else 
+		else
 			return 0
-		fi 
+		fi
 
 		#------------ PDU TYPE
-		if [[ $packet =~ Event\ type:\ ([^|\(]*)\  ]]; then 
+		if [[ $packet =~ Event\ type:\ ([^|\(]*)\  ]]; then
 			pdu_type=${BASH_REMATCH[1]}
 			pdu_type=${pdu_type##* }
-		else 
+		else
 			return 0
-		fi 
+		fi
 
 		#------------ ADVERTISEMENT TYPE
-		if [[ $packet =~ Random ]] || [[ $packet =~ Public ]]; then 
+		if [[ $packet =~ Random ]] || [[ $packet =~ Public ]]; then
 			tx_type=${BASH_REMATCH^^}
 			tx_type=${tx_type:0:4}
-		fi 
+		fi
 
-		#------------ RSSI 
-		if [[ $packet =~ RSSI[^:]*?:([^|\(]*) ]]; then 
+		#------------ RSSI
+		if [[ $packet =~ RSSI[^:]*?:([^|\(]*) ]]; then
 			rssi_value=${BASH_REMATCH[1]}
 			rssi_value=${rssi_value//[^-0-9]/}
-		fi 
+		fi
 
 		#------------ NAME
-		if [[ $packet =~ Name[^:]{0,}:\ {0,}([^|\(]*)\ {0,}(\||$|\() ]]; then 
+		if [[ $packet =~ Name[^:]{0,}:\ {0,}([^|\(]*)\ {0,}(\||$|\() ]]; then
 			gap_name_str=${BASH_REMATCH[1]}
 			gap_name_str=$(trim_whitespace "$gap_name_str")
-		fi 
+		fi
 
 		#------------ MANUFACTURER OF RADIO
-		if [[ $packet =~ Company:\ {0,}([^|\(]*)\ {0,}(\||$|\() ]]; then 
+		if [[ $packet =~ Company:\ {0,}([^|\(]*)\ {0,}(\||$|\() ]]; then
 			manufacturer=${BASH_REMATCH[1]}
 			manufacturer=$(trim_whitespace "$manufacturer")
-		fi 
+		fi
 
 		#------------ ADVERTISEMENT
-		if [[ $packet =~ Data:\ {0,}([^|\(]*)\ {0,}(\||$|\() ]]; then 
+		if [[ $packet =~ Data:\ {0,}([^|\(]*)\ {0,}(\||$|\() ]]; then
 			adv_data=${BASH_REMATCH[1]}
-		fi 
+		fi
 
 		#------------ DEVICE TYPE
-		if [[ $packet =~ Type:\ {0,}([^|\(]*)\ (\||$|\() ]]; then 
+		if [[ $packet =~ Type:\ {0,}([^|\(]*)\ (\||$|\() ]]; then
 			device_type=${BASH_REMATCH[1]}
-		fi 
+		fi
 
-		#------------ FLAGS 
-		if [[ $packet =~ Flags:\ {0,}([^|\(]*)(\||$|\() ]]; then 
+		#------------ FLAGS
+		if [[ $packet =~ Flags:\ {0,}([^|\(]*)(\||$|\() ]]; then
 			flags=${BASH_REMATCH[1]}
-		fi 
+		fi
 
-		#------------ OEM DATA 
-		if [[ $packet =~ 1\ entry\|\ {1,}([^|\(]*)\ {1,}(\||$|\() ]]; then 
+		#------------ OEM DATA
+		if [[ $packet =~ 1\ entry\|\ {1,}([^|\(]*)\ {1,}(\||$|\() ]]; then
 			oem_data=${BASH_REMATCH[1]}
-		fi 
+		fi
 
-		if [ "$tx_type" == "PUBL" ]; then 
+		if [ "$tx_type" == "PUBL" ]; then
 			#PRINT ALL PUBLIC BEACONS
-			printf "%s\n" "$tx_type$received_mac_address|$pdu_type|$gap_name_str|$rssi_value|$adv_data|$manufacturer|$device_type|$flags|$oem_data" > main_pipe
+			printf "%s\n" "$tx_type$received_mac_address|$pdu_type|$gap_name_str|$rssi_value|$adv_data|$manufacturer|$device_type|$flags|$oem_data" | mqtt_pipe_send
 
 		elif [ "$tx_type" == "RAND" ]; then
-		 
-			if [ "$pdu_type" == "ADV_IND" ] || [ "$pdu_type" == "ADV_NONCONN_IND" ] || [ "$pdu_type" == "SCAN_RSP" ] ; then 
+
+			if [ "$pdu_type" == "ADV_IND" ] || [ "$pdu_type" == "ADV_NONCONN_IND" ] || [ "$pdu_type" == "SCAN_RSP" ]; then
 				#IF THIS DOES NOT HAVE A UUID, PROCESS AS GENERIC BEACON
-				should_ignore=false 
-				[ "$tx_type" == "RAND" ] && [ -n "$rssi_value" ] && [[ "$PREF_RSSI_IGNORE_BELOW" -gt "$rssi_value" ]] && should_ignore=true 
+				should_ignore=false
+				[ "$tx_type" == "RAND" ] && [ -n "$rssi_value" ] && [[ "$PREF_RSSI_IGNORE_BELOW" -gt "$rssi_value" ]] && should_ignore=true
 
 				#IF WE HAVE A NAME, DEFINITELY REPORT
-				[ -n "$gap_name_str" ] && should_ignore=false 
+				[ -n "$gap_name_str" ] && should_ignore=false
 
-				if [ "$should_ignore" == false ]; then 
+				if [ "$should_ignore" == false ]; then
 					#REPORT TO MAIN LOOP
-					printf "%s\n" "$tx_type$received_mac_address|$pdu_type|$gap_name_str|$rssi_value|$adv_data|$manufacturer|$device_type|$flags|$oem_data" > main_pipe
-				fi 
-			fi 
-		fi 
+					printf "%s\n" "$tx_type$received_mac_address|$pdu_type|$gap_name_str|$rssi_value|$adv_data|$manufacturer|$device_type|$flags|$oem_data" | mqtt_pipe_send
+				fi
+			fi
+		fi
 	fi
 }
 
 # ----------------------------------------------------------------------------------------
 # BLUETOOTH LE RAW PACKET ANALYSIS
 # ----------------------------------------------------------------------------------------
-btle_text_listener () {
-    while true; do 
-	    #LOCAL VALUES 
+btle_text_listener() {
+	while true; do
+		#LOCAL VALUES
 		local packet
-		local line 
-			
+		local line
+
 		#DEFINE VARAIBLES
 		while IFS= read -r line; do
 			if [[ $line =~ ^\> ]] || [[ $line =~ ^\< ]] || [[ $line =~ RSSI ]]; then
 				[[ $line =~ RSSI ]] && packet="$packet|$line"
 
-				if [[ $packet =~ ^\> ]]; then 
-					btle_text_processor "$packet" & 
+				if [[ $packet =~ ^\> ]]; then
+					btle_text_processor "$packet" &
 					disown "$!"
-				fi 
+				fi
 
 				packet=""
 				packet=$line
-			else 		
-				packet="$packet|$line" 
+			else
+				packet="$packet|$line"
 			fi
 		done < <(timeout --signal SIGINT 400 stdbuf -o0 btmon 2>&1)
-	done 
+	done
 	#REPORT ERROR
-	(>&2 echo "error! irrecoverable btle_text_listener error")
+	(echo >&2 "error! irrecoverable btle_text_listener error")
 }
 
 # ----------------------------------------------------------------------------------------
 # BLUETOOTH LE RAW PACKET ANALYSIS
 # ----------------------------------------------------------------------------------------
-btle_listener () {	
+btle_listener() {
 	#DEFINE VARAIBLES
 	local packet=""
 	local complete_packet_str_length=0
-	
+
 	while IFS= read -r line; do
 		# packets start with ">" or "<"
 		if [[ $line =~ ^\> ]] || [[ $line =~ ^\< ]]; then
@@ -264,18 +261,18 @@ btle_listener () {
 			complete_packet_str_length=0
 
 			if [[ "$packet" =~ ^\>\ 04\ 3E* ]]; then
-				local packet_len=$(echo $packet | awk '{print "ibase=16;"$4}' | bc )
-				complete_packet_str_length=$((( packet_len + 3) * 3  + 1))
-			fi 
+				local packet_len=$(echo $packet | awk '{print "ibase=16;"$4}' | bc)
+				complete_packet_str_length=$(((packet_len + 3) * 3 + 1))
+			fi
 		else
 			# continue building the packet
 			packet="$packet $line"
 
 			#PROCESS A PACKET WHEN IT IS COMPLETE
-			if [ "$complete_packet_str_length" == "${#packet}" ]; then 
+			if [ "$complete_packet_str_length" == "${#packet}" ]; then
 				btle_packet_processor "$packet"
 				packet=""
-			fi 
+			fi
 		fi
 	done < <(timeout --signal SIGINT 900 stdbuf -o0 hcidump -i $PREF_HCI_DEVICE --raw)
 }
